version: '3'

services:
  snapserver:
    image: 'firefrei/snapcast:latest'
    restart: always
    environment:
      # See README.md for all environment options.
      TZ: Etc/UTC
    volumes:
      # Snapcast: Configuration and run-time data
      - snapcast-data:/app/data/
      - snapcast-config:/app/config/
      #- ./config_snapcast/:/app/config/

      # NGINX: HTTPS certificates
      nginx-certs:/app/certs/
      #- ./nginx_certs/:/app/certs/


    # Network Alternative 1: Bridge container directly into your home network
    networks:
      bridged-home-network:
        #ipv4_address: <desired-ip-of-container>

    # Network Alternative 2: Use port-forwarding of host ports
    ports:
      # Snapcast Ports
      - '1704-1705:1704-1705'
      - '1780:1780'
      # AirPlay ports
      - '3689:3689'
      - '5000-5005:5000-5005'
      - '6000-6005:6000-6005/udp'
      # Avahi ports
      - '5353:5353'
      # NGINX ports
      - '443:443'


volumes:
  snapcast-config:
  snapcast-data:
  nginx-certs:


# Network Alternative 1
networks:
  bridged-home-network:
    external: true
